# Generated by Django 5.2.17 on 2026-08-21 05:28

import apps.core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlineapplication',
            name='certificate_file',
            field=models.FileField(blank=True, help_text='Sertifikadu Pre-Sekundária (PDF/JPG/PNG, máximu 2MB)', null=True, upload_to='applications/certificates/', validators=[apps.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png']), apps.core.validators.FileSizeValidator(2)]),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='status',
            field=models.CharField(choices=[('present', 'Iha'), ('absent', 'Falta'), ('late', 'Tardi'), ('excused', 'Justifika')], default='present', max_length=20),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='status',
            field=models.CharField(choices=[('draft', 'Raskunhu'), ('issued', 'Emite'), ('revoked', 'Revoga')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='gradeentry',
            name='term',
            field=models.PositiveSmallIntegerField(default=1, help_text='Períodu (1–4)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)]),
        ),
        migrations.AlterField(
            model_name='onlineapplication',
            name='desired_course_text',
            field=models.CharField(blank=True, help_text='Se kursu seidauk iha lista', max_length=200),
        ),
        migrations.AlterField(
            model_name='onlineapplication',
            name='status',
            field=models.CharField(choices=[('new', 'Foun'), ('reviewing', 'Analiza'), ('accepted', 'Simu'), ('rejected', 'Rejeita'), ('waitlist', 'Lista hein')], db_index=True, default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='timetableslot',
            name='weekday',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Segunda'), (2, 'Tersa'), (3, 'Kuarta'), (4, 'Kinta'), (5, 'Sesta'), (6, 'Sábadu')]),
        ),
    ]
