# Generated by Django 5.2.17 on 2026-08-21 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_application_certificate_and_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationCriterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'application criterion',
                'verbose_name_plural': 'application criteria',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_open', models.BooleanField(default=True, help_text='Se desliga, formuláriu kandidatura taka (non-active).')),
                ('title', models.CharField(default='Kandidatura online', max_length=200)),
                ('intro', models.TextField(blank=True, default='Preenxe formuláriu. Ekipa eskola sei analiza no kontakta ita liuhusi korreiu ka telefone.')),
                ('closed_message', models.TextField(blank=True, default='Kandidatura online taka ona. Favor kontakta eskola ba informasaun tanba tinan letivu oin mai.')),
                ('min_age', models.PositiveSmallIntegerField(default=15)),
                ('max_age', models.PositiveSmallIntegerField(default=21)),
                ('opens_at', models.DateTimeField(blank=True, null=True)),
                ('closes_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'application settings',
                'verbose_name_plural': 'application settings',
            },
        ),
    ]
