# Generated by Django 5.2.17 on 2026-08-12 12:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('students', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ez: TI-A, Peska-1', max_length=80)),
                ('level', models.PositiveSmallIntegerField(default=1, help_text='Nível / ano')),
                ('capacity', models.PositiveIntegerField(default=30)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classrooms', to='courses.academicyear')),
                ('adviser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advised_classes', to='teachers.teacher')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classrooms', to='courses.course')),
            ],
            options={
                'verbose_name': 'class room',
                'verbose_name_plural': 'class rooms',
                'ordering': ['academic_year', 'course', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_number', models.CharField(max_length=50, unique=True)),
                ('enrollment_date', models.DateField(default=django.utils.timezone.localdate)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('active', 'Ativo'), ('completed', 'Concluído'), ('withdrawn', 'Desistiu'), ('transferred', 'Transferido')], db_index=True, default='active', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='courses.academicyear')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='courses.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='students.student')),
            ],
            options={
                'verbose_name': 'enrollment',
                'verbose_name_plural': 'enrollments',
                'ordering': ['-enrollment_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('completed', 'Concluído'), ('transferred', 'Transferido'), ('dropped', 'Saiu')], db_index=True, default='active', max_length=20)),
                ('assigned_at', models.DateField(default=django.utils.timezone.localdate)),
                ('left_at', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_classes', to='courses.academicyear')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_assignments', to='students.classroom')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='class_assignments', to='students.student')),
            ],
            options={
                'verbose_name': 'student class',
                'verbose_name_plural': 'student classes',
                'ordering': ['-academic_year__start_date', 'student__last_name'],
            },
        ),
        migrations.AddConstraint(
            model_name='classroom',
            constraint=models.UniqueConstraint(fields=('course', 'academic_year', 'name'), name='uniq_classroom_course_year_name'),
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(fields=('student', 'course', 'academic_year'), name='uniq_enrollment_student_course_year'),
        ),
        migrations.AddConstraint(
            model_name='studentclass',
            constraint=models.UniqueConstraint(fields=('student', 'classroom', 'academic_year'), name='uniq_student_class_assignment'),
        ),
    ]
