"""Role group names and permission maps for the school portal."""

SUPER_ADMIN = "SUPER_ADMIN"
SCHOOL_ADMIN = "SCHOOL_ADMIN"
ACADEMIC_STAFF = "ACADEMIC_STAFF"
EDITOR = "EDITOR"
TEACHER = "TEACHER"
STUDENT = "STUDENT"

ROLE_CHOICES = (
    (SUPER_ADMIN, "Super Admin"),
    (SCHOOL_ADMIN, "School Admin"),
    (ACADEMIC_STAFF, "Academic Staff"),
    (EDITOR, "Editor"),
    (TEACHER, "Teacher"),
    (STUDENT, "Student"),
)

ALL_ROLES = [code for code, _ in ROLE_CHOICES]

ROLE_LABELS = {code: label for code, label in ROLE_CHOICES}

ROLE_DESCRIPTIONS = {
    SUPER_ADMIN: "Asesu kompletu ba sistema tomak. La bele limita iha painél.",
    SCHOOL_ADMIN: "Jere eskola, konteúdu, uza-na'in no dadus akademiku.",
    ACADEMIC_STAFF: "Jere estudante, profesór, kursu, nota no asisténsia.",
    EDITOR: "Jere konteúdu públiku: notísia, eventu, pájina no dokumentu.",
    TEACHER: "Haree turma, marka asisténsia no rai nota.",
    STUDENT: "Haree dadus rasik: nota, asisténsia, oráriu no dokumentu.",
}

# Actions shown in the dashboard RBAC matrix.
RBAC_ACTIONS = (
    ("view", "Haree"),
    ("add", "Kria"),
    ("change", "Hadia"),
    ("delete", "Hamoos"),
    ("publish", "Publika"),
)

# Curated modules. First permission in each action is the primary checkbox state.
RBAC_MODULES = [
    {
        "key": "news",
        "label": "Notísia sira",
        "actions": {
            "view": ["news.view_news", "news.view_newscategory"],
            "add": ["news.add_news", "news.add_newscategory"],
            "change": ["news.change_news", "news.change_newscategory"],
            "delete": ["news.delete_news", "news.delete_newscategory"],
            "publish": ["news.publish_news"],
        },
    },
    {
        "key": "events",
        "label": "Eventu sira",
        "actions": {
            "view": ["events.view_event"],
            "add": ["events.add_event"],
            "change": ["events.change_event"],
            "delete": ["events.delete_event"],
            "publish": ["events.publish_event"],
        },
    },
    {
        "key": "pages",
        "label": "Pájina CMS",
        "actions": {
            "view": ["pages.view_page"],
            "add": ["pages.add_page"],
            "change": ["pages.change_page"],
            "delete": ["pages.delete_page"],
            "publish": ["pages.publish_page"],
        },
    },
    {
        "key": "documents",
        "label": "Dokumentu sira",
        "actions": {
            "view": ["documents.view_document", "documents.view_documentcategory"],
            "add": ["documents.add_document", "documents.add_documentcategory"],
            "change": ["documents.change_document", "documents.change_documentcategory"],
            "delete": ["documents.delete_document", "documents.delete_documentcategory"],
            "publish": ["documents.publish_document"],
        },
    },
    {
        "key": "gallery",
        "label": "Galeria",
        "actions": {
            "view": ["gallery.view_galleryalbum", "gallery.view_galleryphoto"],
            "add": ["gallery.add_galleryalbum", "gallery.add_galleryphoto"],
            "change": ["gallery.change_galleryalbum", "gallery.change_galleryphoto"],
            "delete": ["gallery.delete_galleryalbum", "gallery.delete_galleryphoto"],
            "publish": ["gallery.publish_galleryalbum"],
        },
    },
    {
        "key": "contact",
        "label": "Mensajen kontaktu",
        "actions": {
            "view": ["contact.view_contactmessage"],
            "change": ["contact.change_contactmessage"],
        },
    },
    {
        "key": "school",
        "label": "Konfigurasaun eskola",
        "actions": {
            "view": ["core.view_school"],
            "change": ["core.change_school"],
        },
    },
    {
        "key": "departments",
        "label": "Departamentu",
        "actions": {
            "view": ["courses.view_department"],
            "add": ["courses.add_department"],
            "change": ["courses.change_department"],
        },
    },
    {
        "key": "years",
        "label": "Tinan akademiku",
        "actions": {
            "view": ["courses.view_academicyear"],
            "add": ["courses.add_academicyear"],
            "change": ["courses.change_academicyear"],
        },
    },
    {
        "key": "courses",
        "label": "Kursu sira",
        "actions": {
            "view": ["courses.view_course"],
            "add": ["courses.add_course"],
            "change": ["courses.change_course"],
            "delete": ["courses.delete_course"],
            "publish": ["courses.publish_course"],
        },
    },
    {
        "key": "subjects",
        "label": "Disiplina sira",
        "actions": {
            "view": ["courses.view_subject"],
            "add": ["courses.add_subject"],
            "change": ["courses.change_subject"],
        },
    },
    {
        "key": "teachers",
        "label": "Profesór sira",
        "actions": {
            "view": ["teachers.view_teacher"],
            "add": ["teachers.add_teacher"],
            "change": ["teachers.change_teacher"],
        },
    },
    {
        "key": "students",
        "label": "Estudante sira",
        "actions": {
            "view": ["students.view_student"],
            "add": ["students.add_student"],
            "change": ["students.change_student"],
        },
    },
    {
        "key": "enrollments",
        "label": "Matríkula sira",
        "actions": {
            "view": ["students.view_enrollment"],
            "add": ["students.add_enrollment"],
            "change": ["students.change_enrollment"],
        },
    },
    {
        "key": "classrooms",
        "label": "Turma sira",
        "actions": {
            "view": ["students.view_classroom"],
            "add": ["students.add_classroom"],
            "change": ["students.change_classroom"],
        },
    },
    {
        "key": "student_classes",
        "label": "Alokasaun turma",
        "actions": {
            "view": ["students.view_studentclass"],
            "add": ["students.add_studentclass"],
            "change": ["students.change_studentclass"],
        },
    },
    {
        "key": "users",
        "label": "Uza-na'in sira",
        "actions": {
            "view": ["accounts.view_user"],
            "add": ["accounts.add_user"],
            "change": ["accounts.change_user"],
        },
    },
    {
        "key": "audit",
        "label": "Rejistu audit",
        "actions": {
            "view": ["accounts.view_auditlog"],
        },
    },
    {
        "key": "attendance",
        "label": "Asisténsia",
        "actions": {
            "view": ["academics.view_attendancerecord"],
            "add": ["academics.add_attendancerecord"],
            "change": ["academics.change_attendancerecord"],
        },
    },
    {
        "key": "grades",
        "label": "Nota sira",
        "actions": {
            "view": ["academics.view_gradeentry"],
            "add": ["academics.add_gradeentry"],
            "change": ["academics.change_gradeentry"],
        },
    },
    {
        "key": "timetable",
        "label": "Oráriu",
        "actions": {
            "view": ["academics.view_timetableslot"],
            "add": ["academics.add_timetableslot"],
            "change": ["academics.change_timetableslot"],
        },
    },
    {
        "key": "certificates",
        "label": "Sertifikadu sira",
        "actions": {
            "view": ["academics.view_certificate"],
            "add": ["academics.add_certificate"],
            "change": ["academics.change_certificate"],
        },
    },
    {
        "key": "applications",
        "label": "Kandidatura sira",
        "actions": {
            "view": [
                "academics.view_onlineapplication",
                "academics.view_applicationcriterion",
                "academics.view_applicationsettings",
            ],
            "add": ["academics.add_applicationcriterion"],
            "change": [
                "academics.change_onlineapplication",
                "academics.change_applicationcriterion",
                "academics.change_applicationsettings",
            ],
            "delete": ["academics.delete_applicationcriterion"],
        },
    },
    {
        "key": "notifications",
        "label": "Notifikasaun sira",
        "actions": {
            "view": ["academics.view_notification"],
            "add": ["academics.add_notification"],
        },
    },
]

# Codename permissions assigned per group (Django auth Permission.codename + app_label).
ROLE_PERMISSIONS = {
    SCHOOL_ADMIN: [
        # CMS
        "view_news",
        "add_news",
        "change_news",
        "delete_news",
        "publish_news",
        "view_newscategory",
        "add_newscategory",
        "change_newscategory",
        "delete_newscategory",
        "view_event",
        "add_event",
        "change_event",
        "delete_event",
        "publish_event",
        "view_page",
        "add_page",
        "change_page",
        "delete_page",
        "publish_page",
        "view_document",
        "add_document",
        "change_document",
        "delete_document",
        "view_documentcategory",
        "add_documentcategory",
        "change_documentcategory",
        "delete_documentcategory",
        "view_galleryalbum",
        "add_galleryalbum",
        "change_galleryalbum",
        "delete_galleryalbum",
        "view_galleryphoto",
        "add_galleryphoto",
        "change_galleryphoto",
        "delete_galleryphoto",
        "view_contactmessage",
        "change_contactmessage",
        "view_school",
        "change_school",
        # Academic
        "view_department",
        "add_department",
        "change_department",
        "view_academicyear",
        "add_academicyear",
        "change_academicyear",
        "view_course",
        "add_course",
        "change_course",
        "publish_course",
        "view_subject",
        "add_subject",
        "change_subject",
        "view_teacher",
        "add_teacher",
        "change_teacher",
        "view_student",
        "add_student",
        "change_student",
        "view_enrollment",
        "add_enrollment",
        "change_enrollment",
        "view_classroom",
        "add_classroom",
        "change_classroom",
        "view_studentclass",
        "add_studentclass",
        "change_studentclass",
        "view_user",
        "change_user",
        "view_auditlog",
        # Phase 9 academics
        "view_attendancerecord",
        "add_attendancerecord",
        "change_attendancerecord",
        "view_gradeentry",
        "add_gradeentry",
        "change_gradeentry",
        "view_timetableslot",
        "add_timetableslot",
        "change_timetableslot",
        "view_certificate",
        "add_certificate",
        "change_certificate",
        "view_onlineapplication",
        "change_onlineapplication",
        "view_applicationcriterion",
        "add_applicationcriterion",
        "change_applicationcriterion",
        "delete_applicationcriterion",
        "view_applicationsettings",
        "change_applicationsettings",
        "view_notification",
        "add_notification",
    ],
    ACADEMIC_STAFF: [
        "view_news",
        "view_event",
        "view_page",
        "view_document",
        "view_galleryalbum",
        "view_department",
        "view_academicyear",
        "add_academicyear",
        "change_academicyear",
        "view_course",
        "add_course",
        "change_course",
        "view_subject",
        "add_subject",
        "change_subject",
        "view_teacher",
        "add_teacher",
        "change_teacher",
        "view_student",
        "add_student",
        "change_student",
        "view_enrollment",
        "add_enrollment",
        "change_enrollment",
        "view_classroom",
        "add_classroom",
        "change_classroom",
        "view_studentclass",
        "add_studentclass",
        "change_studentclass",
        "view_attendancerecord",
        "add_attendancerecord",
        "change_attendancerecord",
        "view_gradeentry",
        "add_gradeentry",
        "change_gradeentry",
        "view_timetableslot",
        "add_timetableslot",
        "change_timetableslot",
        "view_certificate",
        "add_certificate",
        "change_certificate",
        "view_onlineapplication",
        "change_onlineapplication",
        "view_applicationcriterion",
        "add_applicationcriterion",
        "change_applicationcriterion",
        "delete_applicationcriterion",
        "view_applicationsettings",
        "change_applicationsettings",
        "view_notification",
        "add_notification",
    ],
    EDITOR: [
        "view_news",
        "add_news",
        "change_news",
        "delete_news",
        "publish_news",
        "view_newscategory",
        "add_newscategory",
        "change_newscategory",
        "view_event",
        "add_event",
        "change_event",
        "delete_event",
        "publish_event",
        "view_page",
        "add_page",
        "change_page",
        "publish_page",
        "view_document",
        "add_document",
        "change_document",
        "view_documentcategory",
        "view_galleryalbum",
        "add_galleryalbum",
        "change_galleryalbum",
        "view_galleryphoto",
        "add_galleryphoto",
        "change_galleryphoto",
        "view_course",
        "view_teacher",
        "view_contactmessage",
        "change_contactmessage",
    ],
    TEACHER: [
        "view_news",
        "view_event",
        "view_course",
        "view_subject",
        "view_student",
        "view_enrollment",
        "view_classroom",
        "view_studentclass",
        "view_teacher",
        "view_document",
        "view_galleryalbum",
        "view_attendancerecord",
        "add_attendancerecord",
        "change_attendancerecord",
        "view_gradeentry",
        "add_gradeentry",
        "change_gradeentry",
        "view_timetableslot",
        "view_certificate",
    ],
    STUDENT: [
        "view_news",
        "view_event",
        "view_course",
        "view_document",
        "view_galleryalbum",
        "view_enrollment",
        "view_studentclass",
        "view_classroom",
        "view_attendancerecord",
        "view_gradeentry",
        "view_timetableslot",
        "view_certificate",
    ],
}
