from django.urls import path

from . import dashboard_views, views

app_name = "accounts"

urlpatterns = [
    path("login/", views.PortalLoginView.as_view(), name="login"),
    path("logout/", views.PortalLogoutView.as_view(), name="logout"),
    path("profile/", views.ProfileView.as_view(), name="profile"),
    path(
        "password/",
        views.PortalPasswordChangeView.as_view(),
        name="password_change",
    ),
    path("dashboard/", views.DashboardHomeView.as_view(), name="dashboard"),
    path("dashboard/news/", views.DashboardNewsView.as_view(), name="dashboard_news"),
    path(
        "dashboard/news/new/",
        dashboard_views.DashboardNewsCreateView.as_view(),
        name="dashboard_news_create",
    ),
    path(
        "dashboard/news/<int:pk>/edit/",
        dashboard_views.DashboardNewsUpdateView.as_view(),
        name="dashboard_news_update",
    ),
    path(
        "dashboard/news/<int:pk>/delete/",
        dashboard_views.DashboardNewsDeleteView.as_view(),
        name="dashboard_news_delete",
    ),
    path(
        "dashboard/news/categories/",
        dashboard_views.DashboardNewsCategoryListView.as_view(),
        name="dashboard_news_categories",
    ),
    path(
        "dashboard/news/categories/new/",
        dashboard_views.DashboardNewsCategoryCreateView.as_view(),
        name="dashboard_news_category_create",
    ),
    path(
        "dashboard/news/categories/<int:pk>/edit/",
        dashboard_views.DashboardNewsCategoryUpdateView.as_view(),
        name="dashboard_news_category_update",
    ),
    path(
        "dashboard/news/categories/<int:pk>/delete/",
        dashboard_views.DashboardNewsCategoryDeleteView.as_view(),
        name="dashboard_news_category_delete",
    ),
    path(
        "dashboard/events/",
        views.DashboardEventsView.as_view(),
        name="dashboard_events",
    ),
    path(
        "dashboard/events/new/",
        dashboard_views.DashboardEventCreateView.as_view(),
        name="dashboard_events_create",
    ),
    path(
        "dashboard/events/<int:pk>/edit/",
        dashboard_views.DashboardEventUpdateView.as_view(),
        name="dashboard_events_update",
    ),
    path(
        "dashboard/events/<int:pk>/delete/",
        dashboard_views.DashboardEventDeleteView.as_view(),
        name="dashboard_events_delete",
    ),
    path(
        "dashboard/courses/",
        views.DashboardCoursesView.as_view(),
        name="dashboard_courses",
    ),
    path(
        "dashboard/courses/new/",
        dashboard_views.DashboardCourseCreateView.as_view(),
        name="dashboard_courses_create",
    ),
    path(
        "dashboard/courses/<int:pk>/edit/",
        dashboard_views.DashboardCourseUpdateView.as_view(),
        name="dashboard_courses_update",
    ),
    path(
        "dashboard/courses/<int:pk>/delete/",
        dashboard_views.DashboardCourseDeleteView.as_view(),
        name="dashboard_courses_delete",
    ),
    path(
        "dashboard/courses/<int:pk>/subjects/",
        dashboard_views.DashboardCourseSubjectListView.as_view(),
        name="dashboard_course_subjects",
    ),
    path(
        "dashboard/courses/<int:pk>/subjects/new/",
        dashboard_views.DashboardSubjectCreateView.as_view(),
        name="dashboard_subject_create",
    ),
    path(
        "dashboard/subjects/<int:pk>/edit/",
        dashboard_views.DashboardSubjectUpdateView.as_view(),
        name="dashboard_subject_update",
    ),
    path(
        "dashboard/students/",
        views.DashboardStudentsView.as_view(),
        name="dashboard_students",
    ),
    path(
        "dashboard/students/new/",
        dashboard_views.DashboardStudentCreateView.as_view(),
        name="dashboard_students_create",
    ),
    path(
        "dashboard/students/<int:pk>/edit/",
        dashboard_views.DashboardStudentUpdateView.as_view(),
        name="dashboard_students_update",
    ),
    path(
        "dashboard/teachers/",
        views.DashboardTeachersView.as_view(),
        name="dashboard_teachers",
    ),
    path(
        "dashboard/teachers/new/",
        dashboard_views.DashboardTeacherCreateView.as_view(),
        name="dashboard_teachers_create",
    ),
    path(
        "dashboard/teachers/<int:pk>/edit/",
        dashboard_views.DashboardTeacherUpdateView.as_view(),
        name="dashboard_teachers_update",
    ),
    path(
        "dashboard/documents/",
        views.DashboardDocumentsView.as_view(),
        name="dashboard_documents",
    ),
    path(
        "dashboard/documents/new/",
        dashboard_views.DashboardDocumentCreateView.as_view(),
        name="dashboard_documents_create",
    ),
    path(
        "dashboard/documents/<int:pk>/edit/",
        dashboard_views.DashboardDocumentUpdateView.as_view(),
        name="dashboard_documents_update",
    ),
    path(
        "dashboard/documents/<int:pk>/delete/",
        dashboard_views.DashboardDocumentDeleteView.as_view(),
        name="dashboard_documents_delete",
    ),
    path(
        "dashboard/documents/categories/",
        dashboard_views.DashboardDocumentCategoryListView.as_view(),
        name="dashboard_document_categories",
    ),
    path(
        "dashboard/documents/categories/new/",
        dashboard_views.DashboardDocumentCategoryCreateView.as_view(),
        name="dashboard_document_category_create",
    ),
    path(
        "dashboard/documents/categories/<int:pk>/edit/",
        dashboard_views.DashboardDocumentCategoryUpdateView.as_view(),
        name="dashboard_document_category_update",
    ),
    path(
        "dashboard/documents/categories/<int:pk>/delete/",
        dashboard_views.DashboardDocumentCategoryDeleteView.as_view(),
        name="dashboard_document_category_delete",
    ),
    path(
        "dashboard/gallery/",
        views.DashboardGalleryView.as_view(),
        name="dashboard_gallery",
    ),
    path(
        "dashboard/gallery/new/",
        dashboard_views.DashboardGalleryCreateView.as_view(),
        name="dashboard_gallery_create",
    ),
    path(
        "dashboard/gallery/<int:pk>/edit/",
        dashboard_views.DashboardGalleryUpdateView.as_view(),
        name="dashboard_gallery_update",
    ),
    path(
        "dashboard/gallery/<int:pk>/delete/",
        dashboard_views.DashboardGalleryDeleteView.as_view(),
        name="dashboard_gallery_delete",
    ),
    path(
        "dashboard/gallery/<int:pk>/photos/",
        dashboard_views.DashboardGalleryPhotoListView.as_view(),
        name="dashboard_gallery_photos",
    ),
    path(
        "dashboard/gallery/<int:pk>/photos/new/",
        dashboard_views.DashboardGalleryPhotoCreateView.as_view(),
        name="dashboard_gallery_photo_create",
    ),
    path(
        "dashboard/gallery/photos/<int:pk>/delete/",
        dashboard_views.DashboardGalleryPhotoDeleteView.as_view(),
        name="dashboard_gallery_photo_delete",
    ),
    path(
        "dashboard/users/",
        views.DashboardUsersView.as_view(),
        name="dashboard_users",
    ),
    path(
        "dashboard/users/new/",
        dashboard_views.DashboardUserCreateView.as_view(),
        name="dashboard_users_create",
    ),
    path(
        "dashboard/users/<int:pk>/edit/",
        dashboard_views.DashboardUserUpdateView.as_view(),
        name="dashboard_users_update",
    ),
    path(
        "dashboard/roles/",
        dashboard_views.DashboardRoleListView.as_view(),
        name="dashboard_roles",
    ),
    path(
        "dashboard/roles/<str:role>/",
        dashboard_views.DashboardRoleUpdateView.as_view(),
        name="dashboard_roles_update",
    ),
    path(
        "dashboard/audit/",
        views.DashboardAuditView.as_view(),
        name="dashboard_audit",
    ),
    path(
        "dashboard/applications/",
        views.DashboardApplicationsView.as_view(),
        name="dashboard_applications",
    ),
    path(
        "dashboard/applications/settings/",
        dashboard_views.DashboardApplicationSettingsView.as_view(),
        name="dashboard_application_settings",
    ),
    path(
        "dashboard/applications/criteria/",
        dashboard_views.DashboardApplicationCriterionListView.as_view(),
        name="dashboard_application_criteria",
    ),
    path(
        "dashboard/applications/criteria/new/",
        dashboard_views.DashboardApplicationCriterionCreateView.as_view(),
        name="dashboard_application_criterion_create",
    ),
    path(
        "dashboard/applications/criteria/<int:pk>/edit/",
        dashboard_views.DashboardApplicationCriterionUpdateView.as_view(),
        name="dashboard_application_criterion_update",
    ),
    path(
        "dashboard/applications/criteria/<int:pk>/delete/",
        dashboard_views.DashboardApplicationCriterionDeleteView.as_view(),
        name="dashboard_application_criterion_delete",
    ),
    path(
        "dashboard/applications/<int:pk>/status/",
        dashboard_views.DashboardApplicationStatusView.as_view(),
        name="dashboard_application_status",
    ),
    path(
        "dashboard/reports/",
        views.DashboardReportsView.as_view(),
        name="dashboard_reports",
    ),
    path(
        "dashboard/reports/students.csv",
        views.StudentsCsvReportView.as_view(),
        name="report_students_csv",
    ),
    path(
        "dashboard/reports/teachers.csv",
        views.TeachersCsvReportView.as_view(),
        name="report_teachers_csv",
    ),
    path(
        "dashboard/reports/enrollments.csv",
        views.EnrollmentsCsvReportView.as_view(),
        name="report_enrollments_csv",
    ),
    path(
        "dashboard/reports/courses.csv",
        views.CoursesCsvReportView.as_view(),
        name="report_courses_csv",
    ),
    path(
        "dashboard/reports/attendance.csv",
        views.AttendanceCsvReportView.as_view(),
        name="report_attendance_csv",
    ),
    path(
        "dashboard/reports/grades.csv",
        views.GradesCsvReportView.as_view(),
        name="report_grades_csv",
    ),
    path(
        "dashboard/reports/applications.csv",
        views.ApplicationsCsvReportView.as_view(),
        name="report_applications_csv",
    ),
    path(
        "dashboard/settings/",
        views.DashboardSettingsView.as_view(),
        name="dashboard_settings",
    ),
]
